c++-mode:
  target: default
  targets:
    default:
      filetypes:
        - cpp-project
      includes:
        - include
        - winlib
        - /usr/include/postgresql
      defines:
        - _FILE_OFFSET_BITS=64
        - __LINUX__
      flags:
        - -xc++
        - -std=c++11
      warnings:
        - all
        - extra
        - everything
      sources:
        - src
      buildcmd: make -j8 -f makefile
    other:
      filetypes:
        - cpp-project
      buildcmd:
        - make -j8 -f makefile
    other 2:
      filetypes:
        - cpp-project
      buildcmd:
        make -j8 -f makefile
  default-target: default
