#!/bin/sh
SRCFILE="$1"
DSTFILE="$2"
test -e /usr/bin/sudo && USER="-o root" || USER="-o richard"
if [ -d "$SRCFILE" ] ; then
	install $USER -d "$DSTFILE"
else
	DSTDIR="`dirname "$DSTFILE"`"
	install -v $USER -d "$DSTDIR"
	install -C -v $USER "$SRCFILE" "$DSTFILE"
fi
